### ISSUE TITLE
MongoDB collections query and return few items

### ISSUE THREAD

**Issue by alakdamEmmy** [mongodb/community#22]
I am practicing and really new to MongoDb database Query. I have three collections data. One collection is customers, one collection is customer's bag and last collection is customer's cloth. Each of them connect with id. I am using MongoDB package for connection and query. i successfully connect my three collection by using [aggregate](https://docs.mongodb.com/manual/aggregation/). I want to filter the data display few items not all

After connecting the collections and it returns me all items from the collection. Now It looks like this:

    {
    	"tests": {
    		"_id": "dsr309458698696",
    		"bagId": 48543,
    		"sellerId": 22259,
    		"firebaseCreatedAt": "2021-03-01T04:42:15.000Z",
    		"sellers": [{
    			"_id": "29394022211031034",
    			"sellerId": 22259,
    			"address": "East London",
    			"city": "London",
    			"email": "john doe",
    			"firebaseCreatedAt": "2021-03-01T04:42:15.000Z",
    			"firstName": "John",
    			"language": "en",
    			"lastName": "doe",
    			"newsletter": false,
    			"phoneNumber": "20485856",
    			"zipCode": "0037300"
    		}],
    		"cloths": [{
    				"_id": "28282",
    				"clothId": 930507,
    				"bagId": 48543,
    				"firebaseCreatedAt": "2021-03-12T07:27:11.000Z",
    				"season": "Summer",
    				"brand": "Vivobarefoot",
    				"info": "Nice condition",
    				"color": "brown",
    				"price": 38.9
    			}
    		]
    	}
    }

But I want to display like this:

    {
    	"tests": {
    		"bagId": 48543,
    		"sellers": [{
    			"address": "East London",
    			"city": "London",
    			"email": "johndoe@yahoo.com",
    			"firstName": "John",
    			"language": "en",
    			"lastName": "doe"
    		}],
    		"cloths": [{
    			"brand": "Vivobarefoot"
    		}]
    	}
    }

I am sure in documentation it has this kind query but I could not find it. 

**This is my code**

      const finalApi = await client
        .db()
        .collection('bags')
        .aggregate(
          [
            {
              $lookup:
              {
                from: "sellers",
                localField: "sellerId",
                foreignField: "sellerId",
                as: "sellers"
              }
            },
            {
              $lookup:
              {
                from: "clothes",
                localField: "bagId",
                foreignField: "bagId",
                as: "cloths"
              }
            },
            { $match: { firebaseCreatedAt: { '$gte': date } } },
          ]
        ).toArray()

**Comment by stennie** [comment]
👋  Hi  @alakdamEmmy! This GitHub repo was intended to be used for sharing resources related to MongoDB User Groups, such as code samples and presentations. 

For general discussion on MongoDB please join the MongoDB Developer Community Forums @ https://community.mongodb.com.

Regards,
Stennie
