### ISSUE TITLE
MongoDB 3.4 Community Deck

### ISSUE THREAD

**Issue by braz** [mongodb/community#4]
Hi @nleite / @shannonbradshaw,

Is there going to be a MongoDB 3.4 slide deck for use in MUGs made available here ?

Thanks!
Eoin

**Comment by nleite** [comment]
Hi @braz, 

We don't handle the MUGs material. That is probably on Joe Drumgoole plate.
We will be supplying some material that will help on the making of such slide deck but not the slide deck itself. 

N.

**Comment by braz** [comment]
Hi @jdrumgoole,

Is this on your plate / TODO list as it'd be a great resource ?

Thanks!
Eoin
